### ISSUE TITLE
Amplifying noise

### ISSUE THREAD

**Issue by adbrebs** [timsainb/noisereduce#22]
First thanks @timsainb for porting this into python!

Unfortunately I have issues on some files for which the noise is actually amplified.

With the default parameters, this is an example of result that I get https://drive.google.com/open?id=1By4_l1kM9s6K013j6iRwQNsVx3Rvu6Nv

I have tried to play with the parameters but it didn't help. Even setting the noise to zero or `prop_decrease` to zero produces similar additional noise.

Please let me know if it is expected, otherwise I will dig into the code. Thanks!

--------

For reference, this is my code:
```python
import librosa
from noisereduce import reduce_noise


file_path = "raw.wav"

s, e = 33.99000000000053, 35.520000000000586

a, sr = librosa.load(file_path, sr=None)

i_s = int(sr*s)
i_e = int(sr*e)
a_noise = a[i_s:i_e]
a_clean = reduce_noise(a, a_noise, prop_decrease=0)


librosa.output.write_wav("noise.wav", a_noise, sr)
librosa.output.write_wav("denoised.wav", a_clean, sr)
```

**Comment by yasersakkaf** [comment]
I implemented your code, but I get thhe following error,

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/installations/anaconda3/envs/v2t/lib/python3.6/site-packages/noisereduce/noisereduce.py", line 225, in reduce_noise
    noise_clip, n_fft, hop_length, win_length, use_tensorflow=use_tensorflow
  File "/data/installations/anaconda3/envs/v2t/lib/python3.6/site-packages/noisereduce/noisereduce.py", line 15, in _stft
    y=y, n_fft=n_fft, hop_length=hop_length, win_length=win_length, center=True
  File "/data/installations/anaconda3/envs/v2t/lib/python3.6/site-packages/librosa/core/spectrum.py", line 161, in stft
    util.valid_audio(y)
  File "/data/installations/anaconda3/envs/v2t/lib/python3.6/site-packages/librosa/util/utils.py", line 159, in valid_audio
    raise ParameterError('data must be floating-point')
librosa.util.exceptions.ParameterError: data must be floating-point
`
