### ISSUE TITLE
ValueError: time_mask_smooth_ms needs to be at least 256ms

### ISSUE THREAD

**Issue by benblackledge** [timsainb/noisereduce#80]
Hi
I keep getting this error with the most basic implementation of Noise Reduce. My wav clip is mono and sample rate 1000Hz. Here is the full traceback:

```
Traceback (most recent call last):
  File "/Users/personal/PycharmProjects/create-wav/clean-wav.py", line 174, in <module>
    y_noisereduce = nr.reduce_noise(y=samples, sr=sr)
  File "/Users/personal/PycharmProjects/create-wav/venv/lib/python3.9/site-packages/noisereduce/noisereduce.py", line 579, in reduce_noise
    sg = SpectralGateNonStationary(
  File "/Users/personal/PycharmProjects/create-wav/venv/lib/python3.9/site-packages/noisereduce/noisereduce.py", line 266, in __init__
    super().__init__(
  File "/Users/personal/PycharmProjects/create-wav/venv/lib/python3.9/site-packages/noisereduce/noisereduce.py", line 115, in __init__
    self._generate_mask_smoothing_filter(freq_mask_smooth_hz, time_mask_smooth_ms)
  File "/Users/personal/PycharmProjects/create-wav/venv/lib/python3.9/site-packages/noisereduce/noisereduce.py", line 136, in _generate_mask_smoothing_filter
    raise ValueError(
ValueError: time_mask_smooth_ms needs to be at least 256ms
```

Snippet of my code:

```
samples, sr = sf.read(file_path)
y_noisereduce = nr.reduce_noise(y=samples, sr=sr)
```

Any suggestions on what might be going on?

Thanks

**Comment by benblackledge** [comment]
Okay looks like an issue with a low sampling rate. I'm studying seismic waves, hence the relatively low frequencies. Looks like this issue appears below 5100hz having tested with upsampling. Can I suggest an addition to the readme if a fix is not easy? A fix would be great though to allow this library to be used for low sr signals.

**Comment by timsainb** [comment]
If you look at the error, 

```
raise ValueError(
                    "freq_mask_smooth_hz needs to be at least {}Hz".format(
                        int((self.sr / (self._n_fft / 2)))
                    )
                )
```

You should be able to drop down the parameter n_fft. Let me know if that works.

**Comment by benblackledge** [comment]
Dropped n_fft down to 128 and it's now working, many thanks!
